//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.EdnevnikServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Professor", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class Professor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Course {
            get {
                return this.CourseField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseField, value) != true)) {
                    this.CourseField = value;
                    this.RaisePropertyChanged("Course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, int[]> CourseGradesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ProfessorIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, int[]> CourseGrades {
            get {
                return this.CourseGradesField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseGradesField, value) != true)) {
                    this.CourseGradesField = value;
                    this.RaisePropertyChanged("CourseGrades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ProfessorIds {
            get {
                return this.ProfessorIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessorIdsField, value) != true)) {
                    this.ProfessorIdsField = value;
                    this.RaisePropertyChanged("ProfessorIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parent", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class Parent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EdnevnikServiceReference.IEdnevnik", CallbackContract=typeof(ConsoleClient.EdnevnikServiceReference.IEdnevnikCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IEdnevnik {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/RegisterProfessor", ReplyAction="http://tempuri.org/IEdnevnik/RegisterProfessorResponse")]
        void RegisterProfessor(ConsoleClient.EdnevnikServiceReference.Professor p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/RegisterProfessor", ReplyAction="http://tempuri.org/IEdnevnik/RegisterProfessorResponse")]
        System.Threading.Tasks.Task RegisterProfessorAsync(ConsoleClient.EdnevnikServiceReference.Professor p);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEdnevnik/GradeStudent")]
        void GradeStudent(ConsoleClient.EdnevnikServiceReference.Student s, int grade);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEdnevnik/GradeStudent")]
        System.Threading.Tasks.Task GradeStudentAsync(ConsoleClient.EdnevnikServiceReference.Student s, int grade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/AddStudent", ReplyAction="http://tempuri.org/IEdnevnik/AddStudentResponse")]
        void AddStudent(ConsoleClient.EdnevnikServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/AddStudent", ReplyAction="http://tempuri.org/IEdnevnik/AddStudentResponse")]
        System.Threading.Tasks.Task AddStudentAsync(ConsoleClient.EdnevnikServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/GetProfessorStudents", ReplyAction="http://tempuri.org/IEdnevnik/GetProfessorStudentsResponse")]
        ConsoleClient.EdnevnikServiceReference.Student[] GetProfessorStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/GetProfessorStudents", ReplyAction="http://tempuri.org/IEdnevnik/GetProfessorStudentsResponse")]
        System.Threading.Tasks.Task<ConsoleClient.EdnevnikServiceReference.Student[]> GetProfessorStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/RegisterParent", ReplyAction="http://tempuri.org/IEdnevnik/RegisterParentResponse")]
        void RegisterParent(ConsoleClient.EdnevnikServiceReference.Parent p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/RegisterParent", ReplyAction="http://tempuri.org/IEdnevnik/RegisterParentResponse")]
        System.Threading.Tasks.Task RegisterParentAsync(ConsoleClient.EdnevnikServiceReference.Parent p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/GetChildsGrades", ReplyAction="http://tempuri.org/IEdnevnik/GetChildsGradesResponse")]
        System.Collections.Generic.Dictionary<string, int[]> GetChildsGrades(ConsoleClient.EdnevnikServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/GetChildsGrades", ReplyAction="http://tempuri.org/IEdnevnik/GetChildsGradesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int[]>> GetChildsGradesAsync(ConsoleClient.EdnevnikServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/GetParentChildren", ReplyAction="http://tempuri.org/IEdnevnik/GetParentChildrenResponse")]
        ConsoleClient.EdnevnikServiceReference.Student[] GetParentChildren();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/GetParentChildren", ReplyAction="http://tempuri.org/IEdnevnik/GetParentChildrenResponse")]
        System.Threading.Tasks.Task<ConsoleClient.EdnevnikServiceReference.Student[]> GetParentChildrenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/AddChild", ReplyAction="http://tempuri.org/IEdnevnik/AddChildResponse")]
        void AddChild(ConsoleClient.EdnevnikServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/AddChild", ReplyAction="http://tempuri.org/IEdnevnik/AddChildResponse")]
        System.Threading.Tasks.Task AddChildAsync(ConsoleClient.EdnevnikServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/GetAllStudents", ReplyAction="http://tempuri.org/IEdnevnik/GetAllStudentsResponse")]
        ConsoleClient.EdnevnikServiceReference.Student[] GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEdnevnik/GetAllStudents", ReplyAction="http://tempuri.org/IEdnevnik/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<ConsoleClient.EdnevnikServiceReference.Student[]> GetAllStudentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEdnevnikCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEdnevnik/NotifyParent")]
        void NotifyParent(string courseName, int grade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEdnevnikChannel : ConsoleClient.EdnevnikServiceReference.IEdnevnik, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EdnevnikClient : System.ServiceModel.DuplexClientBase<ConsoleClient.EdnevnikServiceReference.IEdnevnik>, ConsoleClient.EdnevnikServiceReference.IEdnevnik {
        
        public EdnevnikClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public EdnevnikClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public EdnevnikClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public EdnevnikClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public EdnevnikClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RegisterProfessor(ConsoleClient.EdnevnikServiceReference.Professor p) {
            base.Channel.RegisterProfessor(p);
        }
        
        public System.Threading.Tasks.Task RegisterProfessorAsync(ConsoleClient.EdnevnikServiceReference.Professor p) {
            return base.Channel.RegisterProfessorAsync(p);
        }
        
        public void GradeStudent(ConsoleClient.EdnevnikServiceReference.Student s, int grade) {
            base.Channel.GradeStudent(s, grade);
        }
        
        public System.Threading.Tasks.Task GradeStudentAsync(ConsoleClient.EdnevnikServiceReference.Student s, int grade) {
            return base.Channel.GradeStudentAsync(s, grade);
        }
        
        public void AddStudent(ConsoleClient.EdnevnikServiceReference.Student s) {
            base.Channel.AddStudent(s);
        }
        
        public System.Threading.Tasks.Task AddStudentAsync(ConsoleClient.EdnevnikServiceReference.Student s) {
            return base.Channel.AddStudentAsync(s);
        }
        
        public ConsoleClient.EdnevnikServiceReference.Student[] GetProfessorStudents() {
            return base.Channel.GetProfessorStudents();
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.EdnevnikServiceReference.Student[]> GetProfessorStudentsAsync() {
            return base.Channel.GetProfessorStudentsAsync();
        }
        
        public void RegisterParent(ConsoleClient.EdnevnikServiceReference.Parent p) {
            base.Channel.RegisterParent(p);
        }
        
        public System.Threading.Tasks.Task RegisterParentAsync(ConsoleClient.EdnevnikServiceReference.Parent p) {
            return base.Channel.RegisterParentAsync(p);
        }
        
        public System.Collections.Generic.Dictionary<string, int[]> GetChildsGrades(ConsoleClient.EdnevnikServiceReference.Student s) {
            return base.Channel.GetChildsGrades(s);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int[]>> GetChildsGradesAsync(ConsoleClient.EdnevnikServiceReference.Student s) {
            return base.Channel.GetChildsGradesAsync(s);
        }
        
        public ConsoleClient.EdnevnikServiceReference.Student[] GetParentChildren() {
            return base.Channel.GetParentChildren();
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.EdnevnikServiceReference.Student[]> GetParentChildrenAsync() {
            return base.Channel.GetParentChildrenAsync();
        }
        
        public void AddChild(ConsoleClient.EdnevnikServiceReference.Student s) {
            base.Channel.AddChild(s);
        }
        
        public System.Threading.Tasks.Task AddChildAsync(ConsoleClient.EdnevnikServiceReference.Student s) {
            return base.Channel.AddChildAsync(s);
        }
        
        public ConsoleClient.EdnevnikServiceReference.Student[] GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.EdnevnikServiceReference.Student[]> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
    }
}
